import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { aiSearch, parseAISearchText } from '../api';
import type { Policy } from '../types';

type Props = {
  query: string;
  policies: Policy[];
  onClear: () => void;
};

export default function AISearchResults({ query, policies, onClear }: Props) {
  const navigate = useNavigate();
  const [streamedText, setStreamedText] = useState('');
  const [done, setDone] = useState(false);
  const [error, setError] = useState('');
  const inFlightFor = useRef<string | null>(null);

  useEffect(() => {
    if (!query) return;
    if (inFlightFor.current === query) return;
    inFlightFor.current = query;

    setStreamedText('');
    setDone(false);
    setError('');

    let cancelled = false;
    aiSearch(query, (fullText) => {
      if (cancelled) return;
      setStreamedText(fullText);
    })
      .then(() => { if (!cancelled) setDone(true); })
      .catch((err) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : 'AI search failed.');
        setDone(true);
      });

    return () => { cancelled = true; };
  }, [query]);

  const parsed = parseAISearchText(streamedText);
  const referenced = policies.filter((p) => parsed.policyIds.includes(p.id));
  const summaryText = parsed.summary || (done ? '' : 'Thinking…');

  function handlePolicyClick(policyId: string) {
    navigate(`/policies/${policyId}`);
  }

  return (
    <div className="ai-results" style={{ marginBottom: 24 }}>
      <div className="ai-disclaimer">
        <strong>AI-Generated Response</strong> — This summary is generated by AI and may be incomplete
        or inaccurate. Always verify information directly in the official policy documents before
        making decisions or taking action.
      </div>

      <div className="card">
        <div className="toolbar">
          <div>
            <span className="ai-badge" style={{ marginBottom: 8, display: 'inline-block' }}>AI</span>
            <h1 className="page-title" style={{ marginBottom: 4 }}>Policy Search Results</h1>
            <p className="ai-query">"{query}"</p>
          </div>
          <button className="secondary-button" type="button" onClick={onClear}>
            Clear results
          </button>
        </div>

        {error ? (
          <div className="form-error">{error}</div>
        ) : (
          <div className="ai-summary">
            {summaryText}
            {!done && parsed.summary && <span className="ai-cursor">▍</span>}
          </div>
        )}

        {referenced.length > 0 && (
          <>
            <hr style={{ margin: '20px 0' }} />
            <p className="ai-refs-title">Referenced Policies — click to view below</p>
            <div className="ai-refs">
              {referenced.map((policy) => (
                <button
                  key={policy.id}
                  className="ai-ref-card"
                  type="button"
                  onClick={() => handlePolicyClick(policy.id)}
                >
                  <div className="ai-ref-category">{policy.category}</div>
                  <div className="ai-ref-title">{policy.title}</div>
                  <div className="ai-ref-summary">{policy.summary}</div>
                </button>
              ))}
            </div>
          </>
        )}

        {done && referenced.length === 0 && parsed.policyIds.length > 0 && (
          <p style={{ color: '#6b7280', marginTop: 16, fontSize: 14 }}>
            Referenced policies could not be found. They may have been removed.
          </p>
        )}
      </div>
    </div>
  );
}
