import { useLocation, useNavigate, Link } from 'react-router-dom';
import type { Policy } from '../types';

type AIResult = {
  summary: string;
  policyIds: string[];
};

type LocationState = {
  query: string;
  result: AIResult;
};

type Props = {
  policies: Policy[];
};

export default function AISearchResults({ policies }: Props) {
  const { state } = useLocation();
  const navigate = useNavigate();

  if (!state?.result) {
    return (
      <div className="card">
        <p>No search results. Use the AI search bar to ask a question about district policy.</p>
      </div>
    );
  }

  const { query, result } = state as LocationState;
  const referenced = policies.filter((p) => result.policyIds.includes(p.id));

  return (
    <div className="ai-results">
      <div className="ai-disclaimer">
        <strong>AI-Generated Response</strong> — This summary is generated by AI and may be incomplete
        or inaccurate. Always verify information directly in the official policy documents before
        making decisions or taking action.
      </div>

      <div className="card">
        <div className="toolbar">
          <div>
            <span className="ai-badge" style={{ marginBottom: 8, display: 'inline-block' }}>AI</span>
            <h1 className="page-title" style={{ marginBottom: 4 }}>Policy Search Results</h1>
            <p className="ai-query">"{query}"</p>
          </div>
          <button className="secondary-button" type="button" onClick={() => navigate('/')}>
            Clear results
          </button>
        </div>

        <div className="ai-summary">{result.summary}</div>

        {referenced.length > 0 && (
          <>
            <hr style={{ margin: '20px 0' }} />
            <h2 className="ai-refs-title">Referenced Policies</h2>
            <div className="ai-refs">
              {referenced.map((policy) => (
                <Link key={policy.id} className="ai-ref-card" to={`/policies/${policy.id}`}>
                  <div className="ai-ref-category">{policy.category}</div>
                  <div className="ai-ref-title">{policy.title}</div>
                  <div className="ai-ref-summary">{policy.summary}</div>
                </Link>
              ))}
            </div>
          </>
        )}

        {referenced.length === 0 && result.policyIds.length > 0 && (
          <p style={{ color: '#6b7280', marginTop: 16, fontSize: 14 }}>
            Referenced policies could not be found. They may have been removed.
          </p>
        )}
      </div>
    </div>
  );
}
