import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { aiSearch, parseAISearchText } from '../api';
import type { Policy } from '../types';

type LocationState = {
  query?: string;
};

type Props = {
  policies: Policy[];
};

export default function AISearchResults({ policies }: Props) {
  const { state } = useLocation();
  const navigate = useNavigate();
  const query = (state as LocationState | null)?.query ?? '';

  const [streamedText, setStreamedText] = useState('');
  const [done, setDone] = useState(false);
  const [error, setError] = useState('');
  const inFlightFor = useRef<string | null>(null);

  useEffect(() => {
    if (!query) return;
    // Guard against React 18 StrictMode double-invocation kicking off two
    // identical requests for the same query.
    if (inFlightFor.current === query) return;
    inFlightFor.current = query;

    setStreamedText('');
    setDone(false);
    setError('');

    let cancelled = false;
    aiSearch(query, (fullText) => {
      if (cancelled) return;
      setStreamedText(fullText);
    })
      .then(() => {
        if (cancelled) return;
        setDone(true);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : 'AI search failed.');
        setDone(true);
      });

    return () => {
      cancelled = true;
    };
  }, [query]);

  if (!query) {
    return (
      <div className="card">
        <p>No search results. Use the AI search bar to ask a question about district policy.</p>
      </div>
    );
  }

  // Live-parse the partial text so the trailing "POLICIES: ..." sentinel
  // doesn't bleed into the visible summary while the model finishes streaming.
  const parsed = parseAISearchText(streamedText);
  const referenced = policies.filter((p) => parsed.policyIds.includes(p.id));
  const summaryText = parsed.summary || (done ? '' : 'Thinking…');

  return (
    <div className="ai-results">
      <div className="ai-disclaimer">
        <strong>AI-Generated Response</strong> — This summary is generated by AI and may be incomplete
        or inaccurate. Always verify information directly in the official policy documents before
        making decisions or taking action.
      </div>

      <div className="card">
        <div className="toolbar">
          <div>
            <span className="ai-badge" style={{ marginBottom: 8, display: 'inline-block' }}>AI</span>
            <h1 className="page-title" style={{ marginBottom: 4 }}>Policy Search Results</h1>
            <p className="ai-query">"{query}"</p>
          </div>
          <button className="secondary-button" type="button" onClick={() => navigate('/')}>
            Clear results
          </button>
        </div>

        {error ? (
          <div className="form-error">{error}</div>
        ) : (
          <div className="ai-summary">
            {summaryText}
            {!done && parsed.summary && <span className="ai-cursor">▍</span>}
          </div>
        )}

        {referenced.length > 0 && (
          <>
            <hr style={{ margin: '20px 0' }} />
            <h2 className="ai-refs-title">Referenced Policies</h2>
            <div className="ai-refs">
              {referenced.map((policy) => (
                <Link key={policy.id} className="ai-ref-card" to={`/policies/${policy.id}`}>
                  <div className="ai-ref-category">{policy.category}</div>
                  <div className="ai-ref-title">{policy.title}</div>
                  <div className="ai-ref-summary">{policy.summary}</div>
                </Link>
              ))}
            </div>
          </>
        )}

        {done && referenced.length === 0 && parsed.policyIds.length > 0 && (
          <p style={{ color: '#6b7280', marginTop: 16, fontSize: 14 }}>
            Referenced policies could not be found. They may have been removed.
          </p>
        )}
      </div>
    </div>
  );
}
